name: Test Module Imports

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-imports:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest
        if [ -f pyproject.toml ]; then
          pip install -e .
        fi
    
    - name: Run import tests
      run: |
        # Add src directory to Python path
        export PYTHONPATH=$PYTHONPATH:$(pwd)/src
        python tests/test_imports.py
    
    - name: Run static import analysis
      run: |
        # Add src directory to Python path
        export PYTHONPATH=$PYTHONPATH:$(pwd)/src
        python tests/test_static_imports.py
